build: false

environment:
  matrix:
    - PYTHON: "C:\\Python39-x64"
      PYTHON_VERSION: "3.9"
      PYTHON_ARCH: "64"


init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - set PATH=C:\Python37;C:\Python37\Scripts;%PATH%
  - python -m pip install --upgrade pip
  - pip install .[tests]

test_script:
  - pytest -r a tests
