classdef SECTORFileWriter < object_oriented_simcap.Writers.EmisFileWriter
    methods (Access = protected)
        function file_header_formatted = get_file_header(self)
            file_header = [...
                '.__  __          _____ _____ _____ _____   ______      _____ ______ _____ _______ ____  _____' self.newline_char ...
                '|  \/  |   /\   / ____|_   _/ ____/ ____| |____  |    / ____|  ____/ ____|__   __/ __ \|  __ \' self.newline_char ...
                '| \  / |  /  \ | |  __  | || |   | |          / /    | (___ | |__ | |       | | | |  | | |__) |' self.newline_char ...
                '| |\/| | / /\ \| | |_ | | || |   | |         / /      \___ \|  __|| |       | | | |  | |  _  /' self.newline_char ...
                '| |  | |/ ____ \ |__| |_| || |___| |____    / /     _ ____) | |___| |____   | | | |__| | | \ \' self.newline_char ...
                '|_|  |_/_/    \_\_____|_____\_____\_____|  /_/     (_)_____/|______\_____|  |_|  \____/|_|  \_\' ...
            ];
            file_header_formatted = object_oriented_simcap.Utils.return_sprintf_compatible_string(...
                file_header...
            );
        end
        function set_THISFILE_DATTYPE_THISFILE_REGIONMODE_region_column_order(self)
            self.THISFILE_REGIONMODE = 'NOTUSED';
            self.THISFILE_DATTYPE = 'SECTORDATA';
        end
        
        function renamed_cell_datablock = return_renamed_cell_datablock(self,cell_datablock)
            renamed_cell_datablock = return_renamed_cell_datablock@object_oriented_simcap.Writers.EmisFileWriter(...
                self,...
                cell_datablock...
            );
            region_idx = strcmpi(renamed_cell_datablock,'Region');
            renamed_cell_datablock{region_idx} = 'COLCODE';
        end
        function header_row_order = get_header_row_order(self)
            header_row_order = {'GAS' 'TODO' 'UNITS' 'COLCODE'};
        end
    end
end
