classdef CONC_INFileReader < object_oriented_simcap.Readers.MAGICCDataFileReader
    methods (Access = protected)
        function tidy_Region_metadata(self)
            self.header_rows_tmp = replace(...
                self.header_rows_tmp,...
                {'YEARS','GLOBAL_MIXINGRATIO'},...
                {'Region','WORLD'}...
            );
        end
        function make_Variable_header_row_in_header_rows_tmp(self)
            repeated_variable_cell = repmat(...
                {self.return_variable_from_filename},...
                1,size(self.header_rows_tmp,2) -1 ...
            );
            variable_row = ['Variable' repeated_variable_cell];
            self.header_rows_tmp = [variable_row;self.header_rows_tmp];
        end
        function variable = return_variable_from_filename(self)
            variable = char(regexp(...
                self.data.full_path_source_file,...
                '(?<=_)\w*(?=_CONC)','match'...
            ));
        end
    end
end