classdef INVERSEEMIS_OUTFileReader < object_oriented_simcap.Readers.MAGICCDataFileReader
    methods (Access = protected)        
        function tidy_Unit_metadata(self)
            self.header_rows_tmp = replace(...
                self.header_rows_tmp,...
                {'UNITS:' '/yr'},...
                {'Unit' ''}...
            );
        end
        function make_Region_header_row_in_header_rows_tmp(self)
            repeated_region_cell = repmat(...
                {'WORLD'},...
                1,size(self.header_rows_tmp,2) -1 ...
            );
            region_row = ['Region' repeated_region_cell];
            self.header_rows_tmp = [region_row;self.header_rows_tmp];
        end
        function tidy_Variable_metadata(self)
            self.header_rows_tmp = replace(...
                self.header_rows_tmp,...
                {'YEARS:' '_INVERSE_EMIS'},...
                {'Variable' ''}...
            );
        end
    end
end